# Generated by Django 5.0.2 on 2024-05-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newcourse',
        ),
    ]
