# Generated by Django 5.0.2 on 2024-05-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0002_delete_tbl_newcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_duration', models.CharField(max_length=30)),
                ('course_price', models.CharField(max_length=30)),
                ('course_details', models.CharField(max_length=30)),
                ('course_enrollmentStatus', models.IntegerField(default='0')),
                ('course_startdate', models.DateField(auto_now_add=True)),
                ('course_enddate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
