# Generated by Django 5.0.2 on 2024-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0004_delete_tbl_newcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_address', models.CharField(max_length=30)),
                ('u_qualification', models.CharField(max_length=30)),
                ('u_email', models.CharField(max_length=30)),
            ],
        ),
    ]
