# Generated by Django 5.0.2 on 2024-05-31 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_initial'),
        ('CourseAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userdetails',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseAdmin.tbl_newevent'),
        ),
    ]
