# Generated by Django 5.0.2 on 2024-05-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_tbl_userdetails_course_id'),
        ('CourseAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_address', models.CharField(max_length=30)),
                ('u_qualification', models.CharField(max_length=30)),
                ('u_email', models.CharField(max_length=30)),
                ('application_status', models.IntegerField(default='0')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CourseAdmin.tbl_newevent')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_userdetails',
        ),
    ]
