# Generated by Django 5.0.2 on 2024-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_duration', models.CharField(max_length=30)),
                ('course_price', models.CharField(max_length=30)),
                ('course_details', models.CharField(max_length=300)),
                ('course_startdate', models.DateField(auto_now_add=True)),
                ('course_enddate', models.DateField(auto_now_add=True)),
                ('enrollment_status', models.IntegerField(default='0')),
            ],
        ),
    ]
