# Generated by Django 5.0.2 on 2024-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newevent',
            name='course_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_newevent',
            name='course_startdate',
            field=models.DateField(),
        ),
    ]
