# Generated by Django 5.0.2 on 2024-04-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newsoloevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_gender', models.CharField(max_length=30)),
                ('e_venue', models.CharField(max_length=30)),
                ('e_date', models.DateField(auto_now_add=True)),
                ('e_time', models.CharField(max_length=30)),
                ('e_details', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_newteamevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_gender', models.CharField(max_length=30)),
                ('e_venue', models.CharField(max_length=30)),
                ('e_date', models.DateField(auto_now_add=True)),
                ('e_time', models.CharField(max_length=30)),
                ('e_details', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
    ]
