# Generated by Django 5.0.2 on 2024-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newteamevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_newteamevent',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_newsoloevent',
        ),
        migrations.DeleteModel(
            name='tbl_newteamevent',
        ),
    ]
