# Generated by Django 5.0.2 on 2024-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0002_tbl_acdemicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.CharField(max_length=50)),
            ],
        ),
    ]
