# Generated by Django 5.0.2 on 2024-04-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0004_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_name', models.CharField(max_length=50)),
                ('coordinator_gender', models.CharField(max_length=50)),
                ('coordinator_contact', models.CharField(max_length=50)),
                ('coordinator_email', models.CharField(max_length=50)),
                ('coordinator_address', models.CharField(max_length=500)),
                ('coordinator_password', models.CharField(max_length=50)),
                ('coordinator_photo', models.FileField(upload_to='Assets/CoordinatorDocs/')),
                ('coordinator_proof', models.FileField(upload_to='Assets/CoordinatorDocs/')),
                ('coordinator_status', models.IntegerField(default='0')),
                ('coordinator_doj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
