# Generated by Django 5.0.2 on 2024-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0005_tbl_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=30)),
                ('a_contact', models.CharField(max_length=30)),
                ('a_email', models.CharField(max_length=30)),
                ('a_password', models.CharField(max_length=30)),
            ],
        ),
    ]
