# Generated by Django 5.0.2 on 2024-04-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0008_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_gender', models.CharField(max_length=30)),
                ('e_date', models.DateField(auto_now_add=True)),
                ('e_time', models.CharField(max_length=30)),
                ('e_details', models.CharField(max_length=30)),
                ('e_venue', models.CharField(max_length=30)),
                ('e_poster', models.CharField(max_length=30)),
                ('type_name', models.CharField(max_length=30)),
                ('teammate_count', models.CharField(max_length=30)),
                ('event_status', models.IntegerField(default='0')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_category')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_coordinator')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_subcategory')),
            ],
        ),
    ]
