# Generated by Django 5.0.2 on 2024-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_newevent',
            name='e_poster',
            field=models.FileField(upload_to='eventphoto/'),
        ),
    ]
