# Generated by Django 5.0.2 on 2024-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdmin', '0011_alter_tbl_newevent_e_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newevent',
        ),
    ]
