# Generated by Django 5.0.2 on 2024-05-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0014_remove_tbl_participants_participant_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(auto_now_add=True)),
                ('result_score', models.IntegerField(max_length=500)),
                ('result_position', models.IntegerField(max_length=500)),
                ('participant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_participants')),
            ],
        ),
    ]
