# Generated by Django 5.0.2 on 2024-05-10 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student', '0016_tbl_participants_tbl_teammates'),
        ('WebAdmin', '0013_tbl_newevent'),
        ('WebCoordinator', '0005_delete_tbl_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(auto_now_add=True)),
                ('result_score', models.IntegerField()),
                ('result_position', models.IntegerField()),
                ('result_status', models.IntegerField(default='0')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_dept')),
                ('participant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_participants')),
            ],
        ),
    ]
