# Generated by Django 5.0.2 on 2024-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminreg',
        ),
        migrations.RemoveField(
            model_name='tbl_coordinator',
            name='place',
        ),
    ]
