# Generated by Django 5.0.2 on 2024-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_delete_tbl_adminreg_remove_tbl_coordinator_place'),
        ('Guest', '0002_alter_tbl_student_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_dept',
        ),
        migrations.DeleteModel(
            name='tbl_sub',
        ),
    ]
