# Generated by Django 5.0.2 on 2024-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_delete_tbl_dept_delete_tbl_sub'),
        ('Student', '0011_alter_tbl_complaint_coordinator_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_coordinator',
        ),
    ]
