# Generated by Django 5.0.2 on 2024-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_delete_tbl_coordinator'),
        ('Coordinator', '0002_remove_tbl_newteamevent_category_and_more'),
        ('Guest', '0003_delete_tbl_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_sem',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
