# Generated by Django 5.0.2 on 2024-04-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Guest', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_status', models.IntegerField(default='0')),
                ('participant_score', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newteamevent')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
                ('teamevent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newsoloevent')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_name', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_participants')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_student')),
            ],
        ),
    ]
