# Generated by Django 5.0.2 on 2024-04-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_tbl_participants_tbl_teammates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_participants',
            old_name='event_id',
            new_name='soloevent_id',
        ),
    ]
