# Generated by Django 5.0.2 on 2024-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_rename_event_id_tbl_participants_soloevent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teammates',
            name='student_id',
        ),
    ]
