# Generated by Django 5.0.2 on 2024-04-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Student', '0004_remove_tbl_teammates_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_participants',
            name='soloevent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newsoloevent'),
        ),
        migrations.AlterField(
            model_name='tbl_participants',
            name='teamevent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newteamevent'),
        ),
    ]
