# Generated by Django 5.0.2 on 2024-04-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_tbl_participants_soloevent_id_and_more'),
        ('WebGuest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student'),
        ),
        migrations.AlterField(
            model_name='tbl_participants',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student'),
        ),
    ]
