# Generated by Django 5.0.2 on 2024-04-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_tbl_complaint_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teammates',
            name='participant_id',
        ),
        migrations.DeleteModel(
            name='tbl_participants',
        ),
        migrations.DeleteModel(
            name='tbl_teammates',
        ),
    ]
