# Generated by Django 5.0.2 on 2024-04-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Student', '0007_remove_tbl_teammates_participant_id_and_more'),
        ('WebGuest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_status', models.IntegerField(default='0')),
                ('participant_score', models.IntegerField(null=True)),
                ('soloevent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newsoloevent')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student')),
                ('teamevent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newteamevent')),
            ],
        ),
    ]
