# Generated by Django 5.0.2 on 2024-04-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_tbl_participants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_participants',
        ),
    ]
