# Generated by Django 5.0.2 on 2024-04-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
        ('Student', '0009_delete_tbl_participants'),
        ('WebGuest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_date', models.IntegerField(null=True)),
                ('participant_status', models.IntegerField(default='0')),
                ('participant_score', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coordinator.tbl_newsoloevent')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student')),
            ],
        ),
    ]
