# Generated by Django 5.0.2 on 2024-04-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_tbl_participants'),
        ('WebAdmin', '0009_tbl_newevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_coordinator'),
        ),
        migrations.AlterField(
            model_name='tbl_participants',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_newevent'),
        ),
        migrations.CreateModel(
            name='tbl_teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_name', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_participants')),
            ],
        ),
    ]
