# Generated by Django 5.0.2 on 2024-04-30 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_remove_tbl_teammates_participant_id_and_more'),
        ('WebAdmin', '0009_tbl_newevent'),
        ('WebGuest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_date', models.DateField(auto_now_add=True)),
                ('participant_status', models.IntegerField(default='0')),
                ('participant_score', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_newevent')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebGuest.tbl_student')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_teammates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammate_name', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_participants')),
            ],
        ),
    ]
