# Generated by Django 5.0.2 on 2024-05-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_tbl_participants_tbl_teammates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_participants',
            name='participant_score',
        ),
    ]
