# Generated by Django 5.0.2 on 2024-05-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_remove_tbl_participants_participant_score'),
        ('WebCoordinator', '0005_delete_tbl_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_teammates',
            name='participant_id',
        ),
        migrations.DeleteModel(
            name='tbl_participants',
        ),
        migrations.DeleteModel(
            name='tbl_teammates',
        ),
    ]
