# Generated by Django 5.0.2 on 2024-04-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_gender', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=500)),
                ('student_password', models.CharField(max_length=50)),
                ('student_photo', models.FileField(upload_to='Assets/StudentDocs/')),
                ('student_proof', models.FileField(upload_to='Assets/StudentDocs/')),
                ('student_status', models.IntegerField(default='0')),
                ('student_doj', models.DateField(auto_now_add=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_dept')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
