# Generated by Django 5.0.2 on 2024-04-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('WebAdmin', '0009_tbl_newevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdmin.tbl_dept'),
        ),
    ]
