# Generated by Django 5.0.2 on 2024-04-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_student_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_student',
        ),
    ]
